# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/design_main_controller_wrapper_0_0.xci
# IP: The module: 'design_main_controller_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_0/controller_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_0 || ORIG_REF_NAME==controller_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_1/controller_xup_xnor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_1 || ORIG_REF_NAME==controller_xup_xnor2_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_2/controller_xup_xnor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_2 || ORIG_REF_NAME==controller_xup_xnor2_0_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_3/controller_xup_xnor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_3 || ORIG_REF_NAME==controller_xup_xnor2_0_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_0/controller_xup_xnor2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_0 || ORIG_REF_NAME==controller_xup_xnor2_3_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_1/controller_xup_xnor2_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_1 || ORIG_REF_NAME==controller_xup_xnor2_3_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_2/controller_xup_xnor2_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_2 || ORIG_REF_NAME==controller_xup_xnor2_3_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_3/controller_xup_xnor2_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_3 || ORIG_REF_NAME==controller_xup_xnor2_3_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_4/controller_xup_xnor2_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_4 || ORIG_REF_NAME==controller_xup_xnor2_3_4} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_5/controller_xup_xnor2_3_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_5 || ORIG_REF_NAME==controller_xup_xnor2_3_5} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_6/controller_xup_xnor2_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_6 || ORIG_REF_NAME==controller_xup_xnor2_3_6} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_7/controller_xup_xnor2_3_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_7 || ORIG_REF_NAME==controller_xup_xnor2_3_7} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and6_0_0/controller_xup_and6_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and6_0_0 || ORIG_REF_NAME==controller_xup_and6_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and6_0_1/controller_xup_and6_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and6_0_1 || ORIG_REF_NAME==controller_xup_and6_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and3_0_0/controller_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and3_0_0 || ORIG_REF_NAME==controller_xup_and3_0_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_ooc.xdc

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/design_main_controller_wrapper_0_0.xci
# IP: The module: 'design_main_controller_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_0/controller_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_0 || ORIG_REF_NAME==controller_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_1/controller_xup_xnor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_1 || ORIG_REF_NAME==controller_xup_xnor2_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_2/controller_xup_xnor2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_2 || ORIG_REF_NAME==controller_xup_xnor2_0_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_0_3/controller_xup_xnor2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_0_3 || ORIG_REF_NAME==controller_xup_xnor2_0_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_0/controller_xup_xnor2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_0 || ORIG_REF_NAME==controller_xup_xnor2_3_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_1/controller_xup_xnor2_3_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_1 || ORIG_REF_NAME==controller_xup_xnor2_3_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_2/controller_xup_xnor2_3_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_2 || ORIG_REF_NAME==controller_xup_xnor2_3_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_3/controller_xup_xnor2_3_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_3 || ORIG_REF_NAME==controller_xup_xnor2_3_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_4/controller_xup_xnor2_3_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_4 || ORIG_REF_NAME==controller_xup_xnor2_3_4} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_5/controller_xup_xnor2_3_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_5 || ORIG_REF_NAME==controller_xup_xnor2_3_5} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_6/controller_xup_xnor2_3_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_6 || ORIG_REF_NAME==controller_xup_xnor2_3_6} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_xnor2_3_7/controller_xup_xnor2_3_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_xnor2_3_7 || ORIG_REF_NAME==controller_xup_xnor2_3_7} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and6_0_0/controller_xup_and6_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and6_0_0 || ORIG_REF_NAME==controller_xup_and6_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and6_0_1/controller_xup_and6_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and6_0_1 || ORIG_REF_NAME==controller_xup_and6_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_xup_and3_0_0/controller_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller_xup_and3_0_0 || ORIG_REF_NAME==controller_xup_and3_0_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_ooc.xdc
