# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Kerem Gurler/EE_Project/EE_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Kerem Gurler/EE_Project/EE_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  {c:/Users/Kerem Gurler/Downloads/Basys3-master/Library}
  {c:/Users/Kerem Gurler/Desktop/IPS}
} [current_project]
set_property ip_output_repo {c:/Users/Kerem Gurler/EE_Project/EE_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/imports/hdl/design_main_wrapper.vhd}}
add_files {{C:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/design_main.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_c_counter_binary_0_0/design_main_c_counter_binary_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/Basys3_Master1.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_controller_wrapper_0_0/src/controller_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/design_main_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Kerem Gurler/Downloads/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Kerem Gurler/Downloads/Basys3_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_main_wrapper -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_main_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_main_wrapper_utilization_synth.rpt -pb design_main_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
