# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Kerem Gurler/Downloads/Basys3_Master.xdc

# Block Designs: bd/design_main/design_main.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main || ORIG_REF_NAME==design_main} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_dff_en_reset_0_0/design_main_xup_dff_en_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_main_xup_dff_en_reset_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_dff_en_reset_0_1/design_main_xup_dff_en_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_dff_en_reset_0_1 || ORIG_REF_NAME==design_main_xup_dff_en_reset_0_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_dff_en_reset_0_2/design_main_xup_dff_en_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_dff_en_reset_0_2 || ORIG_REF_NAME==design_main_xup_dff_en_reset_0_2} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_0_0/design_main_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_0_0 || ORIG_REF_NAME==design_main_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_0_1/design_main_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_0_1 || ORIG_REF_NAME==design_main_xup_inv_0_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_1_0/design_main_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_1_0 || ORIG_REF_NAME==design_main_xup_inv_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_clk_divider_0_0/design_main_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_clk_divider_0_0 || ORIG_REF_NAME==design_main_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xlconstant_0_0/design_main_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xlconstant_0_0 || ORIG_REF_NAME==design_main_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_2_to_1_mux_0_0/design_main_xup_2_to_1_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_2_to_1_mux_0_0 || ORIG_REF_NAME==design_main_xup_2_to_1_mux_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_2_to_1_mux_1_0/design_main_xup_2_to_1_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_2_to_1_mux_1_0 || ORIG_REF_NAME==design_main_xup_2_to_1_mux_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xlconstant_1_0/design_main_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xlconstant_1_0 || ORIG_REF_NAME==design_main_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_0_0/design_main_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_0_0 || ORIG_REF_NAME==design_main_xup_and3_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_0_1/design_main_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_0_1 || ORIG_REF_NAME==design_main_xup_and3_0_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_0_2/design_main_xup_and3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_0_2 || ORIG_REF_NAME==design_main_xup_and3_0_2} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_0_3/design_main_xup_and3_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_0_3 || ORIG_REF_NAME==design_main_xup_and3_0_3} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or2_0_0/design_main_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or2_0_0 || ORIG_REF_NAME==design_main_xup_or2_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_c_counter_binary_0_0/design_main_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_c_counter_binary_0_0 || ORIG_REF_NAME==design_main_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_2_0/design_main_xup_and3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_2_0 || ORIG_REF_NAME==design_main_xup_and3_2_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_4_0/design_main_xup_and3_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_4_0 || ORIG_REF_NAME==design_main_xup_and3_4_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_4_1/design_main_xup_and3_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_4_1 || ORIG_REF_NAME==design_main_xup_and3_4_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or5_0_1/design_main_xup_or5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or5_0_1 || ORIG_REF_NAME==design_main_xup_or5_0_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_0_10/design_main_xup_and4_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_0_10 || ORIG_REF_NAME==design_main_xup_and4_0_10} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_0_11/design_main_xup_and4_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_0_11 || ORIG_REF_NAME==design_main_xup_and4_0_11} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_0_12/design_main_xup_and4_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_0_12 || ORIG_REF_NAME==design_main_xup_and4_0_12} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_0_13/design_main_xup_and4_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_0_13 || ORIG_REF_NAME==design_main_xup_and4_0_13} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_0_14/design_main_xup_and4_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_0_14 || ORIG_REF_NAME==design_main_xup_and4_0_14} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or2_1_1/design_main_xup_or2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or2_1_1 || ORIG_REF_NAME==design_main_xup_or2_1_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_0_0/design_main_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_0_0 || ORIG_REF_NAME==design_main_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_4_0/design_main_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_4_0 || ORIG_REF_NAME==design_main_xup_inv_4_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_5_0/design_main_xup_and4_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_5_0 || ORIG_REF_NAME==design_main_xup_and4_5_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_5_1/design_main_xup_and4_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_5_1 || ORIG_REF_NAME==design_main_xup_and4_5_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_0_0/design_main_xup_and5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_0_0 || ORIG_REF_NAME==design_main_xup_and5_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_1_0/design_main_xup_and5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_1_0 || ORIG_REF_NAME==design_main_xup_and5_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_1_1/design_main_xup_and5_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_1_1 || ORIG_REF_NAME==design_main_xup_and5_1_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_5_2/design_main_xup_and4_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_5_2 || ORIG_REF_NAME==design_main_xup_and4_5_2} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_5_3/design_main_xup_and4_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_5_3 || ORIG_REF_NAME==design_main_xup_and4_5_3} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_5_4/design_main_xup_and4_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_5_4 || ORIG_REF_NAME==design_main_xup_and4_5_4} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or2_2_0/design_main_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or2_2_0 || ORIG_REF_NAME==design_main_xup_or2_2_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_1_0/design_main_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_1_0 || ORIG_REF_NAME==design_main_xup_and2_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_11_0/design_main_xup_and4_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_11_0 || ORIG_REF_NAME==design_main_xup_and4_11_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_11_1/design_main_xup_and4_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_11_1 || ORIG_REF_NAME==design_main_xup_and4_11_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or6_0_1/design_main_xup_or6_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or6_0_1 || ORIG_REF_NAME==design_main_xup_or6_0_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_3_0/design_main_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_3_0 || ORIG_REF_NAME==design_main_xup_inv_3_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_3_1/design_main_xup_inv_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_3_1 || ORIG_REF_NAME==design_main_xup_inv_3_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_3_2/design_main_xup_inv_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_3_2 || ORIG_REF_NAME==design_main_xup_inv_3_2} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_3_0/design_main_xup_and5_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_3_0 || ORIG_REF_NAME==design_main_xup_and5_3_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_3_1/design_main_xup_and5_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_3_1 || ORIG_REF_NAME==design_main_xup_and5_3_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_7_0/design_main_xup_inv_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_7_0 || ORIG_REF_NAME==design_main_xup_inv_7_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_7_0/design_main_xup_and3_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_7_0 || ORIG_REF_NAME==design_main_xup_and3_7_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_5_0/design_main_xup_and5_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_5_0 || ORIG_REF_NAME==design_main_xup_and5_5_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or6_1_0/design_main_xup_or6_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or6_1_0 || ORIG_REF_NAME==design_main_xup_or6_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and4_10_0/design_main_xup_and4_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and4_10_0 || ORIG_REF_NAME==design_main_xup_and4_10_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and5_5_1/design_main_xup_and5_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and5_5_1 || ORIG_REF_NAME==design_main_xup_and5_5_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or4_1_1/design_main_xup_or4_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or4_1_1 || ORIG_REF_NAME==design_main_xup_or4_1_1} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and3_8_0/design_main_xup_and3_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and3_8_0 || ORIG_REF_NAME==design_main_xup_and3_8_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or5_0_0/design_main_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or5_0_0 || ORIG_REF_NAME==design_main_xup_or5_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_dff_en_0_0/design_main_xup_dff_en_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_dff_en_0_0 || ORIG_REF_NAME==design_main_xup_dff_en_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_2_0/design_main_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_2_0 || ORIG_REF_NAME==design_main_xup_and2_2_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_8_0/design_main_xup_inv_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_8_0 || ORIG_REF_NAME==design_main_xup_inv_8_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_storage_wrapper_0_0/design_main_storage_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_storage_wrapper_0_0 || ORIG_REF_NAME==design_main_storage_wrapper_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_seg7_wrapper_0_0/design_main_seg7_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_seg7_wrapper_0_0 || ORIG_REF_NAME==design_main_seg7_wrapper_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_controller_wrapper_0_0/design_main_controller_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_controller_wrapper_0_0 || ORIG_REF_NAME==design_main_controller_wrapper_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or4_0_0/design_main_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or4_0_0 || ORIG_REF_NAME==design_main_xup_or4_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or3_0_0/design_main_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or3_0_0 || ORIG_REF_NAME==design_main_xup_or3_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or2_3_0/design_main_xup_or2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or2_3_0 || ORIG_REF_NAME==design_main_xup_or2_3_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or3_1_0/design_main_xup_or3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or3_1_0 || ORIG_REF_NAME==design_main_xup_or3_1_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_dff_0_0/design_main_xup_dff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_dff_0_0 || ORIG_REF_NAME==design_main_xup_dff_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_inv_9_0/design_main_xup_inv_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_inv_9_0 || ORIG_REF_NAME==design_main_xup_inv_9_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_3_0/design_main_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_3_0 || ORIG_REF_NAME==design_main_xup_and2_3_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_4_0/design_main_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_4_0 || ORIG_REF_NAME==design_main_xup_and2_4_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_5_0/design_main_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_5_0 || ORIG_REF_NAME==design_main_xup_and2_5_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_and2_6_0/design_main_xup_and2_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_and2_6_0 || ORIG_REF_NAME==design_main_xup_and2_6_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_xup_or3_2_0/design_main_xup_or3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_xup_or3_2_0 || ORIG_REF_NAME==design_main_xup_or3_2_0} -quiet] -quiet

# XDC: bd/design_main/design_main_ooc.xdc
