# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/design_main_seg7_wrapper_0_0.xci
# IP: The module: 'design_main_seg7_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconstant_1_0/seg7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconstant_1_0 || ORIG_REF_NAME==seg7_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconstant_0_0/seg7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconstant_0_0 || ORIG_REF_NAME==seg7_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_seg7display_0_0/seg7_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_seg7display_0_0 || ORIG_REF_NAME==seg7_seg7display_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_0_0/seg7_bin2BCD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_0_0 || ORIG_REF_NAME==seg7_bin2BCD_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconcat_1_0/seg7_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconcat_1_0 || ORIG_REF_NAME==seg7_xlconcat_1_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xup_and_vector_0_1/seg7_xup_and_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xup_and_vector_0_1 || ORIG_REF_NAME==seg7_xup_and_vector_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_0_1/seg7_bin2BCD_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_0_1 || ORIG_REF_NAME==seg7_bin2BCD_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_1_0/seg7_bin2BCD_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_1_0 || ORIG_REF_NAME==seg7_bin2BCD_1_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/Basys3_Master1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_seg7_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_ooc.xdc

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/design_main_seg7_wrapper_0_0.xci
# IP: The module: 'design_main_seg7_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconstant_1_0/seg7_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconstant_1_0 || ORIG_REF_NAME==seg7_xlconstant_1_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconstant_0_0/seg7_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconstant_0_0 || ORIG_REF_NAME==seg7_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_seg7display_0_0/seg7_seg7display_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_seg7display_0_0 || ORIG_REF_NAME==seg7_seg7display_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_0_0/seg7_bin2BCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_0_0 || ORIG_REF_NAME==seg7_bin2BCD_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xlconcat_1_0/seg7_xlconcat_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xlconcat_1_0 || ORIG_REF_NAME==seg7_xlconcat_1_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_xup_and_vector_0_1/seg7_xup_and_vector_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_xup_and_vector_0_1 || ORIG_REF_NAME==seg7_xup_and_vector_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_0_1/seg7_bin2BCD_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_0_1 || ORIG_REF_NAME==seg7_bin2BCD_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_bin2BCD_1_0/seg7_bin2BCD_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg7_bin2BCD_1_0 || ORIG_REF_NAME==seg7_bin2BCD_1_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/Basys3_Master1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_seg7_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_seg7_wrapper_0_0/src/seg7_ooc.xdc
