# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/design_main_storage_wrapper_0_0.xci
# IP: The module: 'design_main_storage_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_0/storage_xup_dff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_0 || ORIG_REF_NAME==storage_xup_dff_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_1/storage_xup_dff_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_1 || ORIG_REF_NAME==storage_xup_dff_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_2/storage_xup_dff_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_2 || ORIG_REF_NAME==storage_xup_dff_0_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_3/storage_xup_dff_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_3 || ORIG_REF_NAME==storage_xup_dff_0_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_4/storage_xup_dff_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_4 || ORIG_REF_NAME==storage_xup_dff_0_4} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_5/storage_xup_dff_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_5 || ORIG_REF_NAME==storage_xup_dff_0_5} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_6/storage_xup_dff_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_6 || ORIG_REF_NAME==storage_xup_dff_0_6} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_7/storage_xup_dff_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_7 || ORIG_REF_NAME==storage_xup_dff_0_7} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_8/storage_xup_dff_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_8 || ORIG_REF_NAME==storage_xup_dff_0_8} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_9/storage_xup_dff_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_9 || ORIG_REF_NAME==storage_xup_dff_0_9} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_10/storage_xup_dff_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_10 || ORIG_REF_NAME==storage_xup_dff_0_10} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_11/storage_xup_dff_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_11 || ORIG_REF_NAME==storage_xup_dff_0_11} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_and2_0_0/storage_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_and2_0_0 || ORIG_REF_NAME==storage_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_ooc.xdc

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/design_main_storage_wrapper_0_0.xci
# IP: The module: 'design_main_storage_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_0/storage_xup_dff_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_0 || ORIG_REF_NAME==storage_xup_dff_0_0} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_1/storage_xup_dff_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_1 || ORIG_REF_NAME==storage_xup_dff_0_1} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_2/storage_xup_dff_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_2 || ORIG_REF_NAME==storage_xup_dff_0_2} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_3/storage_xup_dff_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_3 || ORIG_REF_NAME==storage_xup_dff_0_3} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_4/storage_xup_dff_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_4 || ORIG_REF_NAME==storage_xup_dff_0_4} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_5/storage_xup_dff_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_5 || ORIG_REF_NAME==storage_xup_dff_0_5} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_6/storage_xup_dff_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_6 || ORIG_REF_NAME==storage_xup_dff_0_6} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_7/storage_xup_dff_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_7 || ORIG_REF_NAME==storage_xup_dff_0_7} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_8/storage_xup_dff_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_8 || ORIG_REF_NAME==storage_xup_dff_0_8} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_9/storage_xup_dff_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_9 || ORIG_REF_NAME==storage_xup_dff_0_9} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_10/storage_xup_dff_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_10 || ORIG_REF_NAME==storage_xup_dff_0_10} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_dff_0_11/storage_xup_dff_0_11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_dff_0_11 || ORIG_REF_NAME==storage_xup_dff_0_11} -quiet] -quiet

# IP: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_xup_and2_0_0/storage_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==storage_xup_and2_0_0 || ORIG_REF_NAME==storage_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/Kerem Gurler/EE_Project/EE_Project.srcs/sources_1/bd/design_main/ip/design_main_storage_wrapper_0_0/src/storage_ooc.xdc
